steps:

    # Install node packages
    - name: node:10.16.3
      entrypoint: npm
      args: ['install']
    
    # Build productive files
    - name: node:10.16.3
      entrypoint: npm
      args: [ 'run', 'build', '--prod' ]
    
    # Deploy to google cloud app engine
    - name: "gcr.io/cloud-builders/gcloud"
      args: ['app', 'deploy', '--version=prod']


      - name: 'gcr.io/cloud-builders/gke-deploy'
      args:
      - 'run'
      - '--image=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
      - '--location=${_ZONE}'
      - '--cluster=${_GKE_CLUSTER}'

      - name: 'gcr.io/cloud-builders/kubectl'
      args:
      - 'create'
      - 'deployment=${_CONTAINERNAME}'
      - '--image=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  
    - name: 'gcr.io/cloud-builders/kubectl'
      args:
      - 'expose'
      - 'deployment=${_CONTAINERNAME}'
      - '--type=LoadBalancer'
      - '--port ${_PORT}' 
      - '--target-port ${_PORT}'