apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-6
  name: nginx-6-service
spec:
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app: nginx-6
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-6
  name: nginx-6
spec:
  selector:
    matchLabels:
      app: nginx-6
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-6
    spec:
      containers:
      - image: gcr.io/tough-bearing-259612/fdeploy:1.0
        imagePullPolicy: IfNotPresent
        name: fdeploy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30